data_paths:
  full_dataset: "data/Premier_League/clean_premiere_league_data/all_seasons_combined.csv"
  pca_dataset: "data/Premier_League/clean_premiere_league_data/pca_results.csv"

output_settings:
  base_path: "results/Premier_League/Binary_Target"
  model_type: "Stacked_Model"
  
excluded_columns:
  - date
  - season
  - home_team
  - away_team
  - target_result
  - target_home_goals
  - target_away_goals

model_parameters:
  random_forest:
    n_estimators: 100
    random_state: 42
  
  logistic_regression:
    max_iter: 1000
    random_state: 42
    
  svm:
    probability: true
    random_state: 42

meta_classifier:  # Changed from meta_model_parameters
  random_forest:
    n_estimators: 100
    random_state: 42
    max_depth: 5

data_split:
  test_size: 0.2
  random_state: 42